"use client";

import React from "react";
import { motion } from "framer-motion";

export default function PrivacyPage() {
    return (
        <>
            <nav className="navbar">
                <div className="container" style={{ maxWidth: "800px" }}>
                    <a href="/" className="nav-logo">
                        <svg viewBox="0 0 24 24" fill="currentColor" width="24" height="24">
                            <path d="M12 2L2 22h20L12 2z"></path>
                        </svg>
                        CloudMeld
                    </a>
                    <ul className="nav-links">
                        <li><a href="/security">Security</a></li>
                        <li><a href="/status">Status</a></li>
                    </ul>
                </div>
            </nav>

            <main>
                <section className="hero" style={{ padding: "8rem 0 4rem", background: "none" }}>
                    <div className="container" style={{ textAlign: "left", maxWidth: "800px" }}>
                        <h1 className="hero-title" style={{ fontSize: "2.5rem", marginBottom: "1rem", textAlign: "left" }}>Privacy Policy</h1>
                        <p className="hero-subtitle" style={{ fontSize: "1.125rem", marginLeft: 0, textAlign: "left", maxWidth: "100%" }}>
                            Data processing procedures and technical storage methodologies adhering to enterprise transparency directives.
                        </p>
                    </div>
                </section>

                <section className="section no-border" style={{ paddingTop: 0 }}>
                    <div className="container" style={{ maxWidth: "800px" }}>
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5 }}
                            style={{ display: "flex", flexDirection: "column", gap: "3rem", color: "var(--text-secondary)", lineHeight: 1.7 }}
                        >
                            <div>
                                <h2 style={{ fontSize: "1.25rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "1rem" }}>1. Data Collection Scope</h2>
                                <p style={{ marginBottom: "1rem" }}>
                                    CloudMeld strictly collects technical parameters necessary for the functional operation and persistent monitoring of deploying environments. This includes domain specifications, deployment telemetry, operational logs, and essential billing identifiers provided during the initialization sequence.
                                </p>
                                <p>
                                    As an infrastructure provider, we do not inherently monitor, access, or parse the encrypted network traffic or payload data passing through your allocated node resources.
                                </p>
                            </div>

                            <div>
                                <h2 style={{ fontSize: "1.25rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "1rem" }}>2. Encryption Models</h2>
                                <p>
                                    Volatile and persistent telemetry data generated by your infrastructure is encrypted at rest using AES-256 standard encryption. Data in transit between the client terminal and the CloudMeld administration backend is secured utilizing TLS 1.3 cryptographic protocols, explicitly prohibiting unencrypted transmission channels.
                                </p>
                            </div>

                            <div>
                                <h2 style={{ fontSize: "1.25rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "1rem" }}>3. Data Retention Framework</h2>
                                <p>
                                    Infrastructure logs and telemetry metrics are retained based on SLA storage constraints and are permanently truncated chronologically. Upon absolute termination of the deployment contract, associated operational and technical routing metadata is definitively scrubbed from edge processing tables.
                                </p>
                            </div>

                            <div>
                                <h2 style={{ fontSize: "1.25rem", fontWeight: 600, color: "var(--text-primary)", marginBottom: "1rem" }}>4. Third-Party Integrations</h2>
                                <p>
                                    Financial throughput and transaction records are directly provisioned via Razorpay APIs. CloudMeld does not temporarily or permanently store raw credit card inputs, banking credentials, or specific fiscal identification pathways internally. For localized tracking regarding invoice generation, referencing our API-linked integration architectures is recommended.
                                </p>
                            </div>

                        </motion.div>
                    </div>
                </section>
            </main>

            <footer className="footer" style={{ marginTop: "4rem" }}>
                <div className="container" style={{ maxWidth: "800px" }}>
                    <div className="footer-bottom" style={{ borderTop: "1px solid var(--border-color)", paddingTop: "2rem" }}>
                        <span>© {new Date().getFullYear()} CloudMeld Hosting.</span>
                        <div style={{ display: "flex", gap: "1rem" }}>
                            <a href="/">Return to Platform</a>
                        </div>
                    </div>
                </div>
            </footer>
        </>
    );
}
